/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:297eae81eefe77b2a0111fdadcbfea04:bbbc6735697fa5fdcf76a5b2d9c50a77:60b9ef50a9c2c935e7b9dbd934922ed8$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
    public class Client
    {

        public const string Hit1_hit1_0 = "hit1/hit1-0";
        public const string Hit1_hit1_1 = "hit1/hit1-1";
        public const string Hit1_hit1_2 = "hit1/hit1-2";
        public const string Hit1_hit1_3 = "hit1/hit1-3";
        public const string Hit1_hit1_4 = "hit1/hit1-4";
        public const string Hit1_hit1_5 = "hit1/hit1-5";
        public const string Hit1_hit1_6 = "hit1/hit1-6";
        public const string Hit1_hit1_7 = "hit1/hit1-7";
        public const string Hit1_hit1_8 = "hit1/hit1-8";
        public const string Hit1_hit1_9 = "hit1/hit1-9";
        public const string Hit1_hit1_10 = "hit1/hit1-10";
        public const string Hit1_hit1_11 = "hit1/hit1-11";
        public const string Hit1_hit1_12 = "hit1/hit1-12";
        public const string Hit1_hit1_13 = "hit1/hit1-13";
        public const string Hit1_hit1_14 = "hit1/hit1-14";
        public const string Hit1_hit1_15 = "hit1/hit1-15";
        public const string Hit1_hit1_16 = "hit1/hit1-16";
        public const string Hit1_hit1_17 = "hit1/hit1-17";
        public const string Hit1_hit1_18 = "hit1/hit1-18";
        public const string Hit2_hit2_0 = "hit2/hit2-0";
        public const string Hit2_hit2_1 = "hit2/hit2-1";
        public const string Hit2_hit2_2 = "hit2/hit2-2";
        public const string Hit2_hit2_3 = "hit2/hit2-3";
        public const string Hit2_hit2_4 = "hit2/hit2-4";
        public const string Hit2_hit2_5 = "hit2/hit2-5";
        public const string Hit2_hit2_6 = "hit2/hit2-6";
        public const string Hit2_hit2_7 = "hit2/hit2-7";
        public const string Hit2_hit2_8 = "hit2/hit2-8";
        public const string Hit2_hit2_9 = "hit2/hit2-9";
        public const string Hit2_hit2_10 = "hit2/hit2-10";
        public const string Hit2_hit2_11 = "hit2/hit2-11";
        public const string Hit2_hit2_12 = "hit2/hit2-12";
        public const string Hit2_hit2_13 = "hit2/hit2-13";
        public const string Hit2_hit2_14 = "hit2/hit2-14";
        public const string Hit2_hit2_15 = "hit2/hit2-15";
        public const string Hit2_hit2_16 = "hit2/hit2-16";
        public const string Hit2_hit2_17 = "hit2/hit2-17";
        public const string Hit2_hit2_18 = "hit2/hit2-18";
        public const string Hit2_hit2_19 = "hit2/hit2-19";
        public const string Hit3_hit3_0 = "hit3/hit3-0";
        public const string Hit3_hit3_1 = "hit3/hit3-1";
        public const string Hit3_hit3_2 = "hit3/hit3-2";
        public const string Hit3_hit3_3 = "hit3/hit3-3";
        public const string Hit3_hit3_4 = "hit3/hit3-4";
        public const string Hit3_hit3_5 = "hit3/hit3-5";
        public const string Hit3_hit3_6 = "hit3/hit3-6";
        public const string Hit3_hit3_7 = "hit3/hit3-7";
        public const string Hit3_hit3_8 = "hit3/hit3-8";
        public const string Hit3_hit3_9 = "hit3/hit3-9";
        public const string Shield1_shield1_0 = "shield1/shield1-0";
        public const string Shield1_shield1_1 = "shield1/shield1-1";
        public const string Shield1_shield1_2 = "shield1/shield1-2";
        public const string Shield1_shield1_3 = "shield1/shield1-3";
        public const string Shield1_shield1_4 = "shield1/shield1-4";
        public const string Shield1_shield1_5 = "shield1/shield1-5";
        public const string Shield1_shield1_6 = "shield1/shield1-6";
        public const string Shield1_shield1_7 = "shield1/shield1-7";
        public const string Shield1_shield1_8 = "shield1/shield1-8";
        public const string Shield1_shield1_9 = "shield1/shield1-9";
        public const string Shield1_shield1_10 = "shield1/shield1-10";
        public const string Shield1_shield1_11 = "shield1/shield1-11";
        public const string Shield1_shield1_12 = "shield1/shield1-12";
        public const string Shield1_shield1_13 = "shield1/shield1-13";
        public const string Shield1_shield1_14 = "shield1/shield1-14";
        public const string Shield1_shield1_15 = "shield1/shield1-15";
        public const string Shield1_shield1_16 = "shield1/shield1-16";
        public const string Shield1_shield1_17 = "shield1/shield1-17";
        public const string Shield1_shield1_18 = "shield1/shield1-18";
        public const string Shield1_shield1_19 = "shield1/shield1-19";
        public const string Hit4_0 = "hit4-0";
        public const string Hit4_1 = "hit4-1";
        public const string Hit4_2 = "hit4-2";
        public const string Hit4_3 = "hit4-3";
        public const string Hit4_4 = "hit4-4";
        public const string Hit4_5 = "hit4-5";
        public const string Hit4_6 = "hit4-6";
        public const string Hit4_7 = "hit4-7";
        public const string Hit4_8 = "hit4-8";
        public const string Hit4_9 = "hit4-9";
        public const string Hit4_10 = "hit4-10";
        public const string Hit4_11 = "hit4-11";
        public const string Hit4_12 = "hit4-12";
        public const string Hit4_13 = "hit4-13";
        public const string Hit4_14 = "hit4-14";
        public const string Hit4_15 = "hit4-15";
        public const string Hit4_16 = "hit4-16";
        public const string Hit4_17 = "hit4-17";
        public const string Hit4_18 = "hit4-18";
    }
}